### ISSUE TITLE
Error on DB table?

### ISSUE THREAD

**Issue by somethingGoneWrong** [kieraneglin/pinchflat#106]
Hi, i just try to run this software via docker but i get error with some db table i think.
The docker image i launch is this:
```
docker create --name CTX_pinchflat --restart unless-stopped -e PUID=1000 -e PGID=1000 -e TZ=Europe/Rome --network net -h pinchflat -p 8945:8945 -v /share_docker/pf_config:/config --mount type=bind,source=/mnt/misc/TEMP_YT/,target=/downloads --log-driver syslog --log-opt tag=DOCKER_pinchflat --log-opt syslog-address=udp://IP_LOCAL:514 keglin/pinchflat:latest
```
these below are the error i get:
```
!! - Edited by admin - !!

This was a database error that was actually a file permissions error. 
The error was improved in #114 and the original error here is no longer relevant
```
i need to fix something? thx

**Comment by gelof2022** [comment]
I'm getting the same error when trying to start the container:

```
10:51:45.386 [error] Exqlite.Connection (#PID<0.131.0>) failed to connect: ** (Exqlite.Error) eacces
10:51:45.386 [error] Exqlite.Connection (#PID<0.132.0>) failed to connect: ** (Exqlite.Error) eacces
10:51:46.944 [error] Exqlite.Connection (#PID<0.131.0>) failed to connect: ** (Exqlite.Error) eacces
10:51:47.602 [error] Exqlite.Connection (#PID<0.132.0>) failed to connect: ** (Exqlite.Error) eacces
10:51:48.320 [error] Could not create schema migrations table. This error usually happens due to the following:
  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)
To fix the first issue, run "mix ecto.create" for the desired MIX_ENV.
To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create", both for the desired MIX_ENV. Alternatively you may
configure Ecto to use another table and/or repository for managing
migrations:
    config :pinchflat, Pinchflat.Repo,
      migration_source: "some_other_table_for_schema_migrations",
      migration_repo: AnotherRepoForSchemaMigrations
The full error report is shown below.
** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2923ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
  1. Ensuring your database is available and that you can connect to it
  2. Tracking down slow queries and making sure they are running fast enough
  3. Increasing the pool_size (although this increases resource consumption)
  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
See DBConnection.start_link/2 for more information
    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1161: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.11.1) lib/ecto/migrator.ex:755: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql 3.11.1) lib/ecto/migrator.ex:563: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.11.1) lib/ecto/migrator.ex:432: Ecto.Migrator.run/4
    (ecto_sql 3.11.1) lib/ecto/migrator.ex:170: Ecto.Migrator.with_repo/3
    nofile:1: (file)
10:51:52.309 [error] Invalid logger handler config: {:pinchflat,
 {:handler_not_added, {:open_failed, ~c"/config/logs/pinchflat.log", :eacces}}}
10:51:52.313 [error] Exqlite.Connection (#PID<0.1976.0>) failed to connect: ** (Exqlite.Error) eacces
10:51:52.313 [error] Exqlite.Connection (#PID<0.1978.0>) failed to connect: ** (Exqlite.Error) eacces
10:51:52.313 [error] Exqlite.Connection (#PID<0.1979.0>) failed to connect: ** (Exqlite.Error) eacces
10:51:52.313 [error] Exqlite.Connection (#PID<0.1980.0>) failed to connect: ** (Exqlite.Error) eacces
10:51:52.315 [error] Exqlite.Connection (#PID<0.1977.0>) failed to connect: ** (Exqlite.Error) eacces
10:51:53.395 [error] Exqlite.Connection (#PID<0.1980.0>) failed to connect: ** (Exqlite.Error) eacces
10:51:53.807 [error] Exqlite.Connection (#PID<0.1977.0>) failed to connect: ** (Exqlite.Error) eacces
10:51:53.931 [error] Exqlite.Connection (#PID<0.1978.0>) failed to connect: ** (Exqlite.Error) eacces
10:51:54.010 [error] Exqlite.Connection (#PID<0.1979.0>) failed to connect: ** (Exqlite.Error) eacces
10:51:54.880 [error] Exqlite.Connection (#PID<0.1976.0>) failed to connect: ** (Exqlite.Error) eacces
10:51:55.313 [notice] Application pinchflat exited: Pinchflat.Application.start(:normal, []) returned an error: shutdown: failed to start child: Pinchflat.Boot.PreJobStartupTasks
    ** (EXIT) an exception was raised:
        ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2999ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
  1. Ensuring your database is available and that you can connect to it
  2. Tracking down slow queries and making sure they are running fast enough
  3. Increasing the pool_size (although this increases resource consumption)
  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
See DBConnection.start_link/2 for more information
            (ecto_sqlite3 0.15.1) lib/ecto/adapters/sqlite3/connection.ex:47: Ecto.Adapters.SQLite3.Connection.prepare_execute/5
            (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:960: Ecto.Adapters.SQL.execute!/5
            (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
            (ecto 3.11.1) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
            (ecto 3.11.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
            (ecto 3.11.1) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one/3
            (pinchflat 0.1.0) lib/pinchflat/settings/settings.ex:62: Pinchflat.Settings.fetch!/3
            (pinchflat 0.1.0) lib/pinchflat/boot/pre_job_startup_tasks.ex:42: Pinchflat.Boot.PreJobStartupTasks.apply_default_settings/0
Kernel pid terminated (application_controller) ("{application_start_failure,pinchflat,{{shutdown,{failed_to_start_child,'Elixir.Pinchflat.Boot.PreJobStartupTasks',{#{message => <<\"connection not available and request was dropped from queue after 2999ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:\n\n  1. Ensuring your database is available and that you can connect to it\n  2. Tracking down slow queries and making sure they are running fast enough\n  3. Increasing the pool_size (although this increases resource consumption)\n  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval\n\nSee DBConnection.start_link/2 for more information\n\">>,reason => queue_timeout,'__struct__' => 'Elixir.DBConnection.ConnectionError','__exception__' => true,severity => error},[{'Elixir.Ecto.Adapters.SQLite3.Connection',prepare_execute,5,[{file,\"lib/ecto/adapters/sqlite3/connection.ex\"},{line,47},{error_info,#{module => 'Elixi
Crash dump is being written to: erl_crash.dump...done
```

**Comment by joshuapeterson** [comment]
I'm seeing the same error on startup

`12:57:16.193 [error] Exqlite.Connection (#PID<0.131.0>) failed to connect: ** (Exqlite.Error) eacces
12:57:16.193 [error] Exqlite.Connection (#PID<0.132.0>) failed to connect: ** (Exqlite.Error) eacces
12:57:17.260 [error] Exqlite.Connection (#PID<0.132.0>) failed to connect: ** (Exqlite.Error) eacces
12:57:18.814 [error] Exqlite.Connection (#PID<0.131.0>) failed to connect: ** (Exqlite.Error) eacces
12:57:19.194 [error] Could not create schema migrations table. This error usually happens due to the following:
  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)
To fix the first issue, run "mix ecto.create" for the desired MIX_ENV.
To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create", both for the desired MIX_ENV. Alternatively you may
configure Ecto to use another table and/or repository for managing
migrations:
    config :pinchflat, Pinchflat.Repo,
      migration_source: "some_other_table_for_schema_migrations",
      migration_repo: AnotherRepoForSchemaMigrations
The full error report is shown below.
** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2990ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
  1. Ensuring your database is available and that you can connect to it
  2. Tracking down slow queries and making sure they are running fast enough
  3. Increasing the pool_size (although this increases resource consumption)
  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
See DBConnection.start_link/2 for more information
    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1161: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.11.1) lib/ecto/migrator.ex:755: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql 3.11.1) lib/ecto/migrator.ex:563: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.11.1) lib/ecto/migrator.ex:432: Ecto.Migrator.run/4
    (ecto_sql 3.11.1) lib/ecto/migrator.ex:170: Ecto.Migrator.with_repo/3
    nofile:1: (file)
12:57:20.102 [error] Invalid logger handler config: {:pinchflat,
 {:handler_not_added, {:open_failed, ~c"/config/logs/pinchflat.log", :eacces}}}
12:57:20.104 [error] Exqlite.Connection (#PID<0.1980.0>) failed to connect: ** (Exqlite.Error) eacces
12:57:20.104 [error] Exqlite.Connection (#PID<0.1976.0>) failed to connect: ** (Exqlite.Error) eacces
12:57:20.104 [error] Exqlite.Connection (#PID<0.1977.0>) failed to connect: ** (Exqlite.Error) eacces
12:57:20.104 [error] Exqlite.Connection (#PID<0.1979.0>) failed to connect: ** (Exqlite.Error) eacces
12:57:20.104 [error] Exqlite.Connection (#PID<0.1978.0>) failed to connect: ** (Exqlite.Error) eacces
12:57:21.382 [error] Exqlite.Connection (#PID<0.1979.0>) failed to connect: ** (Exqlite.Error) eacces
12:57:21.541 [error] Exqlite.Connection (#PID<0.1977.0>) failed to connect: ** (Exqlite.Error) eacces
12:57:21.936 [error] Exqlite.Connection (#PID<0.1976.0>) failed to connect: ** (Exqlite.Error) eacces
12:57:21.982 [error] Exqlite.Connection (#PID<0.1980.0>) failed to connect: ** (Exqlite.Error) eacces
12:57:22.105 [notice] Application pinchflat exited: Pinchflat.Application.start(:normal, []) returned an error: shutdown: failed to start child: Pinchflat.Boot.PreJobStartupTasks
    ** (EXIT) an exception was raised:
        ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2000ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
  1. Ensuring your database is available and that you can connect to it
  2. Tracking down slow queries and making sure they are running fast enough
  3. Increasing the pool_size (although this increases resource consumption)
  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
See DBConnection.start_link/2 for more information
            (ecto_sqlite3 0.15.1) lib/ecto/adapters/sqlite3/connection.ex:47: Ecto.Adapters.SQLite3.Connection.prepare_execute/5
            (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:960: Ecto.Adapters.SQL.execute!/5
            (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
            (ecto 3.11.1) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
            (ecto 3.11.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
            (ecto 3.11.1) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one/3
            (pinchflat 0.1.0) lib/pinchflat/settings/settings.ex:62: Pinchflat.Settings.fetch!/3
            (pinchflat 0.1.0) lib/pinchflat/boot/pre_job_startup_tasks.ex:42: Pinchflat.Boot.PreJobStartupTasks.apply_default_settings/0
Kernel pid terminated (application_controller) ("{application_start_failure,pinchflat,{{shutdown,{failed_to_start_child,'Elixir.Pinchflat.Boot.PreJobStartupTasks',{#{message => <<\"connection not available and request was dropped from queue after 2000ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:\n\n  1. Ensuring your database is available and that you can connect to it\n  2. Tracking down slow queries and making sure they are running fast enough\n  3. Increasing the pool_size (although this increases resource consumption)\n  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval\n\nSee DBConnection.start_link/2 for more information\n\">>,reason => queue_timeout,'__struct__' => 'Elixir.DBConnection.ConnectionError','__exception__' => true,severity => error},[{'Elixir.Ecto.Adapters.SQLite3.Connection',prepare_execute,5,[{file,\"lib/ecto/adapters/sqlite3/connection.ex\"},{line,47},{error_info,#{module => 'Elixi
Crash dump is being written to: erl_crash.dump...done`

**Comment by tiritibambix** [comment]
Same same

**Comment by kieraneglin** [comment]
This reads to me like the app doesn't have permission to write the database file to the config location. I'll see if I can replicate this later today, but what happens if you use `--user=99:100` and remove the current PUID/PGID options?

This will help me confirm the issue

**Comment by kieraneglin** [comment]
Also, can you tell me a little bit about your environment? Is it x86 or arm? Are you using WSL? Stuff like that

**Comment by tiritibambix** [comment]
I'm running docker on an amd64 machine. Nothing less, nothing more.
I set permission to 777 and tried with no puid/pgid specified, with 99:100 and with 0:0.
Still get the same error.

**Comment by kieraneglin** [comment]
@tiritibambix that helps, thanks! Would you mind posting your full Docker command?

**Comment by kieraneglin** [comment]
Just checked and I was able to repro this issue by making the config folder not writable by the Docker user. Here's the output of the config dir from `ls -la` _when everything is working_: `drwxr-xr-x 1 nobody users  28 Mar  1 16:55 pinchflat-dev/` and I'm running the user as `99:100`.

What's the output of `ls -la` in regards to that directory for you?

**Comment by tiritibambix** [comment]
For the record, I don't know much about all this, so please bare with me.
 I converted the docker command to docker-compose because I use portainer:
```
version: "3.3"
services:
  pinchflat:
    environment:
      - BASIC_AUTH_USERNAME=username
      - BASIC_AUTH_PASSWORD=password
      - PUID=998
      - PGID=100
    ports:
      - 8945:8945
    volumes:
      - /path/Pinchflat/config:/config
      - /path/Pinchflat/downloads:/downloads
    image: keglin/pinchflat:latest
```
998:100 is my docker user:group. As mentioned above, I also tried none, 99:100 and 0:0
`path/Pinchflat/config` remains empty after each attempt no matter the config.

`ls -la` in `path/Pinchflat/config` outputs this:
```
drwxr-sr-x 2 root users 4096 Mar 23 16:08 .
drwxrwsrwx 4 root users 4096 Mar 23 16:08 ..

```

**Comment by tiritibambix** [comment]
Ok, I got it to work.
I previously set permissions to `/config` and `/downloads` to `777`, but I had do do it to the parent directory `/Pinchflat` and set it recursively. I then `chown -R 998:100 /Pinchflat` and use `998:100` in my config.

Thanks for your assistance, it help me figure it out.

Now I can try Pinchflat :D

**Comment by kieraneglin** [comment]
Glad to hear you got it sorted! You may want to see if `755` works instead of `777` - it's not much, but it's a _little_ safer.

Thanks for the help! I'll keep this issue open for a bit longer while I add a preflight check for permissions that's easier to read + improve the docs 🤙

**Comment by tiritibambix** [comment]
It won't work with `755` or `775` :(

**Comment by kieraneglin** [comment]
Hmm. One last thing to try - does it work if you first run `chown -R nobody /path/Pinchflat` then `chmod -R 755 /path/Pinchflat`?

I'll be the first to say that I'm not a docker/linux admin expert so thanks for bearing with me!

**Comment by somethingGoneWrong** [comment]
> Also, can you tell me a little bit about your environment? Is it x86 or arm? Are you using WSL? Stuff like that

x86 on LXC container

**Comment by tiritibambix** [comment]
If `chown -R nobody /path/Pinchflat` that means you want me to try with `99:100` ?

**Comment by kieraneglin** [comment]
> that means you want me to try with 99:100?

If you could try with both `998:100` and `99:100` I'd really appreciate it! This is helping me streamline install for people in the future so I appreciate your help 🙌

**Comment by somethingGoneWrong** [comment]
> This reads to me like the app doesn't have permission to write the database file to the config location. I'll see if I can replicate this later today, but what happens if you use `--user=99:100` and remove the current PUID/PGID options?
> 
> This will help me confirm the issue

yeah this work, but why i can not use a specific PUID/PGUID?

**Comment by tiritibambix** [comment]
> If you could try with both `998:100` and `99:100` I'd really appreciate it! This is helping me streamline install for people in the future so I appreciate your help 🙌

It works with both :)

**Comment by kieraneglin** [comment]
> yeah this work, but why i can not use a specific PUID/PGUID?

The Docker container isn't set to do anything with PUID/PGUID env vars like you might find in a Linuxserver container. This is based on personal preference because, to my understanding, the PUID/PGUID approach starts the container as `root` and eventually downgrades based on the PUID/PGUID. 

In contrast, `--user` runs all the commands as the specified user, never running as root (unless you user `--user root`, of course). This is my preference since I figure there's no need to run as root if _nothing_ in my container actually needs root access. You can still specify the _UID and GID_ that you want with `--user <UID>:<GID>` or any other valid `--user` option outlined [here](https://docs.docker.com/engine/reference/run/#user). 

Again, I'm _not_ a Docker master but this system seems to work well. I'll update the docs later today to clarify this point

**Comment by gelof2022** [comment]
I'm still confused with what I need to do:

1) Do I add UID/GID to 'environment' variable and set it to a) my UID/GID b) 99:100 c) 998:100

```
version: "3.3"
services:
  pinchflat:
    ports:
      - 8945:8945
    environment:
      - TZ = Australia/Sydney
      - UID = 998
      - GID = 100
    volumes:
      - /volume1/docker/pinchflat/config:/config
      - /volume1/docker/pinchflat/downloads:/downloads
    image: keglin/pinchflat:latest
networks: {}
```

2) Something else?

**Comment by kieraneglin** [comment]
So just to be ultimately clear, the PUID and PGID environment variables actually have nothing to do with Docker or Linux by default. It's a convention put into place by Linuxserver (and others), but the presence of those environment variables doesn't actually _do_ anything automatically. So you can remove those guys entirely. 

Instead, add a line of `user: '99:100'` to that service (you can see an example in one of the recent messages of #105 - I'm on my phone right now or I would paste it myself). You may also have to change the ownership of those directories with the commands mentioned earlier 🤙🏻

**Comment by gelof2022** [comment]
Got it!

Works now!

Below is my compose:

```
version: "3.3"
services:
  pinchflat:
    ports:
      - 8945:8945
    environment:
      - TZ = Australia/Sydney
    volumes:
      - /volume1/docker/pinchflat/config:/config
      - /volume1/docker/pinchflat/downloads:/downloads
    image: keglin/pinchflat:latest
    user: '1030:100'
networks: {}
```
I also made mu user the owner of all the relevant directories (these previously were own by a different user).

**Comment by kieraneglin** [comment]
I'm closing this issue now that #114 is merged in. It's still relevant of course, but I'm hoping that the improved error messaging will help.

Discussion is still open so please post here if you're having issues! I'm closing it because I don't feel it's an issue _of the app_, rather it's one of the host machine. But that doesn't mean you can't post if you need support!

**Comment by C8opmBM** [comment]
You _don't feel_ this is an issue of the app. Well, it is an issue of the app.

**Comment by kieraneglin** [comment]
@C8opmBM please keep it civil. This is objectively not an issue _of the app_, it's an issue of the host filesystem that _impacts_ the app. Indeed I could just crank all permissions and have it run as root (like many other containers do), but that'd have negative implications for any other app that tries to interact with your downloaded content. 

I'm sure there's some way to resolve this, but I'm not a DevOps guy and I've exhausted my ideas. I'm open to pull requests!

**Comment by Brancliff** [comment]
It's me, I'm the person still having the problem
From the startup error message:

"Or adding `user: '99:100'` to the Pinchflat service of your Docker Compose"

I did that and I'm still having problems. Here's my Docker-compose:

version: "3.3"
services:
  pinchflat:
    image: keglin/pinchflat:latest
    user: '99:100'
    ports:
      - '4009:8945' # Yeah I changed this part just for convenience, it shouldn't be a factor
    volumes:
      - /path/to/config:/config
      - /path/to/downloads:/downloads

**Comment by tiritibambix** [comment]
> It's me, I'm the person still having the problem From the startup error message:
> 
> "Or adding `user: '99:100'` to the Pinchflat service of your Docker Compose"
> 
> I did that and I'm still having problems. Here's my Docker-compose:
> 
> version: "3.3" services: pinchflat: image: keglin/pinchflat:latest user: '99:100' ports: - '4009:8945' # Yeah I changed this part just for convenience, it shouldn't be a factor volumes: - /path/to/config:/config - /path/to/downloads:/downloads

Be sure to read all asmnwers in the topic.
There is a folder permission issue that should be handled this way before deploying:
```
mkdir -vp .../Pinchflat/{config,downloads} \
&& chown -R nobody /Pinchflat \
&& chmod -R 755 /Pinchflat
```

**Comment by kieraneglin** [comment]
I'm hoping the changes in #157 will improve the permissions issue in some cases 🤙

**Comment by hozza** [comment]
> I'm hoping the changes in #157 will improve the permissions issue in some cases 🤙. Those will be deployed as part of `v0.1.7`

I'm having issues with starting due to perms also. I understand that you're going for a better approach than the env var PUID/PGIU convention, but it's not clear how to actually make it work IMO. I'd rather not change my directory perms as my user can read/write as needed.

Does #157 change the steps mentioned above to make perms work?

I have directories owned by user, docker is run as deamon by root, I'm using docker-compose (via sudo) and usually set PUID/PGIU to 1000. I've tried "user: 1000:1000" and "user: 1000:100" without any luck.

**Comment by kieraneglin** [comment]
@hozza #157 _should_ clear it up so that if the host's docker user can write to the directories, so can the container. That should be out later today!

**Comment by akzov** [comment]
I believe this is because it's using 0o755 when it needs to be 0o760 to allow group members to write

**Comment by crispybegs** [comment]
i've been using pinchflat for ages without any issue but i just moved my download directory to a separate nas which is mounted across the network on my pinchflat server at /mnt/terramaster/media/audio/podcasts and now i've run into this permissions issue for the first time.

i tried adding `user: '99:100'` into my compse but got exactly the same result. The user on the pinchflat server is 1000:1000 but the user on the nas is 0:0 so im unsure how to resolve that. I'm reluctant to start changing permissons on the mounted nas folder as there are so many other services that hook into it that i can imagine it being a house of cards waiting to blow over.

any tips?

**Comment by joeyfigaro** [comment]
I could also use some insight here—user/group on machine running pinchflat is `1000:1000` and the container's PGID/PUID have been configured properly. Download directories are owned by `root`.

**Comment by joeyfigaro** [comment]
To add to this, it looks like config directories/files created by Pinchflat also have their ownsership set to `root`.
