### ISSUE TITLE
Feature Request: delete old media after a certain time frame

### ISSUE THREAD

**Issue by Serph91P** [kieraneglin/pinchflat#113]
In regards of this topic https://github.com/kieraneglin/pinchflat/issues/60

Time-Window Management: The system should automatically track the upload dates of videos. Only videos uploaded within the last two weeks from the current date should be eligible for download and storage.

Automatic Updates: The container must periodically check the specified YouTube channel for new video uploads. Any new content that fits within the two-week window should be downloaded automatically.

Storage Optimization: As new videos are downloaded, videos that fall outside of the two-week window should be automatically deleted from the storage. This ensures that the storage does not become overwhelmed with outdated content.

Configurability: Users should be able to configure the specific start and end dates for the two-week window, allowing for flexibility in how the content is refreshed.

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

The first two points are already in place - you can set indexing frequency and cutoff date when configuring a source. 

For the latter two points, those features are on my radar but it will be a while before I add them. Pinchflat is built for archival and preservation first and foremost and deletion of media is antithetical to that (although I do totally understand the appeal). This is something I'll get around to once I'm fully happy with the features it offers around archiving data. 

In the meantime, if you're using Plex I believe it can be set to delete old media. I'm not sure if that's true for jellyfin or others, but it's worth looking into. If that's a deal breaker, I'm pretty sure both Tube Archivist and Tubesync offer deletion of old media!

---

I'm going to be closing this issue because this is already on my internal feature tracker and it's something that isn't currently planned. I'll reopen this issue once I can give it an estimated timeline.

**Comment by kieraneglin** [comment]
@Heppie I'm still thinking through how I would approach this. Another option is to keep only a certain _number_ of videos instead of basing it on date. This would benefit channels that upload less frequently, but it would quickly cycle through content of channels that upload daily. 

I'm not sure which of these two approaches I'm going to take, but it would definitely be one or the other (not both). Do you have any preference between these options?

**Comment by Heppie** [comment]
I personally prefer a time period

**Comment by Nairou** [comment]
+1 for time period.

Different channels post videos at different rates. Keep the last "10 videos" might mean a few days worth for one, or a few years worth for another.

**Comment by kieraneglin** [comment]
Deletion after `x` days will be coming out in `v0.1.7` which should be released later today 🎉
