### ISSUE TITLE
Plex and NFO files

### ISSUE THREAD

**Issue by reefland** [kieraneglin/pinchflat#117]
Not sure if this is a Plex issue or Plex configuration issue...

1) Add a new source to Media Profile for Plex, using `Output path template` of:
```
{{ source_custom_name }}/Season {{ season_from_date }}/{{ season_episode_from_date }} - {{ title }}.{{ ext }}
```
Enabled the following:
* Download of Subtitles
* Download of Autogenerated Subtitles
* Download of Thumbnail
* Embed Thumbail
* Download Metadata
* Embed Metadata
* Download NFO data
* Download Series Images
2) Wait for source downloads to complete
3) In Plex I made a Library type of "TV Show" (I assume this is correct) and select "Scan Library Files", wait for it to complete.
* Channel is divided into seasons based on year as expected
* Poster & Background image is set correctly
* Each episode has proper icon shown

However, nothing else is populated within Plex, such as no channel summary, no episode title or summary, etc. I assume this is a short-coming of Plex itself not processing the respective *.NFO files?? 

Under Plex > Settings > Agents > Shows > Personal Media Shows both `Personal Media Shows` and `Local Media Assets` are enabled.

Is there something else needed to get Plex to process the *.NFO files per channel/episode?

**Comment by kieraneglin** [comment]
That output path looks good to me and that's the biggest thing with Plex! Plex doesn't support NFO files which is annoying, but what can ya' do.

It sounds like you're done everything right in step 3, but there's one other thing to try. You likely want to enable `Prefer local metadata` and `Use local assets` which are found in "TV Shows" > Manage Library > Edit > Advanced. You may then have to `Refresh Metadata` in the options of the given show you're interested in.

This _may_ have some implication in how your non-youtube Plex content displays metadata, but I haven't seen any issues yet!

---

In regards to `no channel summary` specifically, I don't think this is something I can fix. This data is stored in the NFO file, but since I can't embed that information in the folder itself I can't think of a way for Plex to pick it up.

There might be some custom Plex NFO agent that solves all these issues, but I haven't found one that I feel comfortable recommending yet.

Anyway, let me know how that works out!

**Comment by reefland** [comment]
Excellent!  enable `Prefer local metadata` and `Use local assets` got episode title and description working. That moves this into the usable category for sure.   Channel summary I can cut & paste manually since its a one time thing.

That's an important tidbit to document if you get around to per media player settings page.

**Comment by kieraneglin** [comment]
Glad to hear you got it working! I've actually already documented it in the [docs](https://github.com/kieraneglin/pinchflat/wiki/Frequently-Asked-Questions#how-do-i-get-media-into-plexjellyfinkodi),  but I'll consider adding it in-app somehow.

Thanks for the report!
