### ISSUE TITLE
UnRAID Docker isn't exposing any ports 

### ISSUE THREAD

**Issue by al-geeker** [kieraneglin/pinchflat#126]
![image](https://github.com/kieraneglin/pinchflat/assets/32320831/c67285e7-e68f-4a37-8a3f-ceb30f21ee8b)

The screenshot above shows the UnRaid Docker section. For some reason, the port mappings are not showing up for Pinchflat like how they show up for the rest of the Docker containers (see the Plex Docker container as an example).

When I select the WebUI option from the Docker container, I get the following: about:blank#blocked

Manually typing in the IP Address:Port works though.

I am not sure if the two issues are related.

Thanks!

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report

It looks like this is a behaviour of Unraid when using a custom bridge/bond when the app doesn't advertise (expose) any ports. It's not clear to me how to resolve this because the UnRAID documentation for app publishing is _very_ outdated, but I'll try updating the Dockerfile and see if that fixes it.

This attempted fix will be included in the next release!

**Comment by kieraneglin** [comment]
I _think_ this will be resolved once [this](https://github.com/kieraneglin/pinchflat/actions/runs/8439131020) actions run completes. Let me know if updating doesn't resolve this issue!

**Comment by al-geeker** [comment]
I removed the Docker container completely and reinstalled it using the UnRaid Community App Store and it now works with the port mappings.

Thanks for the quick fix!
