### ISSUE TITLE
FR: Prevent adding the same Source URL more than once

### ISSUE THREAD

**Issue by bbrodka2** [kieraneglin/pinchflat#152]
Please consider adding some code to prevent adding the same Source URL more then once when adding a new source.

Thanks fot your hard work, great app

Running via UnRaid great

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report

This was actually originally in place but I removed it in #99. The reason is that, with the title filtering feature, I found myself creating duplicate sources that use different title regexes. 

I'll consider adding something back where it's unique across URL and title regex
