### ISSUE TITLE
Incorrect Year

### ISSUE THREAD

**Issue by LoganJFisher** [kieraneglin/pinchflat#183]
The metadata for the year in downloaded videos is a bit screwy. For example, a video made on January 31, 2020 has its year as "20200131" rather than just "2020".

_Originally posted by @LoganJFisher in https://github.com/kieraneglin/pinchflat/issues/167#issuecomment-2048036049_

**Comment by kieraneglin** [comment]
Hmm. This is a `yt-dlp` bug that it seems they don't intend to fix (see [here](https://github.com/yt-dlp/yt-dlp/issues/3087) and [here](https://github.com/yt-dlp/yt-dlp/issues/3766)). It appears to be with a limitation of certain file formats and the recommended workaround is to add `--parse-metadata "%(release_year,upload_date).4s:(?P<meta_date>.+)"`

I'll look into this to see if I can determine _why_ they've left it like this and what the implications would be from changing this at the app-level

**Comment by kieraneglin** [comment]
Still looking into this! This ended up being an absolute rabbit hole of conflicting standards, 3rd party app support, and incorrect documentation. I can see how why `yt-dlp` didn't feel comfortable making a sweeping change here but I'm hoping I can be a little more authoritative since the app forces mp4/m4a container types.

I'm also fighting off quite a cold so this may take a while yet, but it's still on my radar!
