### ISSUE TITLE
Add id3 metadata to audio downloads

### ISSUE THREAD

**Issue by dhruvbhutani** [kieraneglin/pinchflat#195]
The metadata embed feature doesn't seem to do this. Or perhaps it's unable to recognise certain aspects of the naming scheme. 

Would it be possible to train this on a per-feed basis? Or perhaps select based on character limits. For eg, I download a few radio shows from YouTube. The naming scheme remains constant. 

BBC Radio One Drum and Bass Show - 18/02/2024
B.O.M BBC Radio One Drum and Bass Mix - 14/04/2024

These are two examples. I'd want to add album / title / perhaps date of release data to ID3 based on the upload name. 

Not sure if this is feasible, but would make pinchflat basically perfect for me.

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report

I don't think `yt-dlp` would add id3 tags to m4a files, but it certainly adds metadata in the XMP format that essentially all media players can read:

![Screenshot 2024-04-22 at 9 19 32 AM](https://github.com/kieraneglin/pinchflat/assets/569917/68640a47-2ef0-4436-b0a5-56d8c9cc4af3)

Can you tell me a little more about what behaviour you're seeing that's not working as you'd expect? Even if you're looking for something that Pinchflat can't/shouldn't support, we might be able to figure something out for you using [metadata modification](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#modifying-metadata) and [custom yt-dlp options](https://github.com/kieraneglin/pinchflat/wiki/%5BAdvanced%5D-Custom-yt%E2%80%90dlp-options).

**Comment by dhruvbhutani** [comment]
Thanks! So, here's what I'm trying to do. 

Let's take this for example: 

B.O.M BBC Radio One Drum and Bass Mix - 14/04/2024 
From the Rev DnB channel. 

I'm wondering if its possible to do title based manipulation for id3. 

So... Artist / Album Artist could be - Rev DnB. 
        Album : BBC Radio One Drum and Bass Mix 
        Date : 14/04/2024 
        
        or 
        
        Title : B.O.M. 14/04/2024 
        
In this specific example, the B.O.M. is a specific guest mix and extracting that for an Album tag would be too hard. But perhaps it is possible to define specific phrases on a per source basis for eg: "BBC Radio One Drum and Bass Mix" which would automatically get appended to the Album field. 

As it stands, Plex Amp identifies the channel name as the artist, but does not have any album at all. Nor is there a date field which makes organization impossible. The music is played back in download order, not chronological. 

Hope this makes sense!

**Comment by kieraneglin** [comment]
Got it. Thank you for the additional info!

Candidly, I don't think this is something the app will ever support natively - it's fairly complicated to get right for all use cases while still being pretty niche. While it is for a different request, I think [this response](https://github.com/kieraneglin/pinchflat/issues/174#issuecomment-2049971620) could shed some light into my approach for including certain features in the app.

That said, I think that [metadata modification](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#modifying-metadata) and [custom yt-dlp options](https://github.com/kieraneglin/pinchflat/wiki/%5BAdvanced%5D-Custom-yt%E2%80%90dlp-options) could indeed solve your issue! The yt-dlp discord or /r/youtubedl subreddit can be really helpful for helping construct the `--parse-metadata` statement you'll need.

As for date field, the `date` is definitely being written to the file's metadata in the partial ISO-8601 format. It could possibly be related to [this issue](https://www.reddit.com/r/plexamp/comments/19e994z/album_date_incorrect_in_plexamp/), but that's outside the scope of Pinchflat.

---

I'm going to close this issue since I don't believe there's any steps for me at the moment. If you disagree or need anything else, don't hesitate to reopen this or another issue!

Thanks again for the report (:
