### ISSUE TITLE
Podcast feed

### ISSUE THREAD

**Issue by sean89503** [kieraneglin/pinchflat#197]
I first want to say I think this is an amazing project. I love the aspect of being able to use a podcast application. It would be really cool if it could hand off the streaming link to the podcast app instead of having to host all the files. I don't know if that would be possible to make a custom profile for just streaming. Can't wait to see what more comes out of this.

**Comment by kieraneglin** [comment]
Hey there, thanks for the report!

I'm not totally sure I understand what you mean by `instead of having to host all the files`. Would you mind providing a little more information?

**Comment by sean89503** [comment]
ya for sure,  so I've been playing around with yt-dip and I see that it provides a stream URL `yt-dlp -F https://www.youtube.com/watch?v={videoID}` it would be nice if when the podcast manager tries to download a file it would redirect it to the most recent URL that's compadable in that list. that way google itself still hosts the file. for downloading.

**Comment by kieraneglin** [comment]
Got it!

I like the idea, but unfortunately it's not compatible with the way Pinchflat fetches and stores data. It's also counter to the spirit of the app since it's fundamentally designed to _escape_ streaming from Google's servers in favour of self-hosting. Besides, audio only takes up like 1MB per minute which is _nothing_ when it comes to storage.

It also may not be possible even in theory without some hard work for a few reasons:

- I suspect most podcast apps won't natively support some of the audio/video formats returned by YouTube
- The format download links expire after a relatively short amount of time so the app would have to constantly re-fetch a fresh one
- I don't think the format links support HTTP range requests in the way that is required to truly stream something

These aren't insurmountable problems, but to solve them you'd probably have to proactively download + convert the media before streaming it yourself. You'd also have to serve the podcast XML from your server. At that point you're pretty much doing what Pinchflat does anyway 🤷‍♂️ .

---

Anyway, thank you once again for the report! Feel free to reply to this issue or open a new one if you have any other questions
