### ISSUE TITLE
How do I set a scheduled index timing?

### ISSUE THREAD

**Issue by dashrandom** [kieraneglin/pinchflat#198]
Hi, I really like pinchflat but I'm having one issue where it  seems that indexing runs all day long and I can't seem to schedule a time so it doesn't coincide with when I need to use internet bandwidth for other more important tasks.

Is there a way to schedule a start time via docker env vars?

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

That functionality isn't possible and is actually by design to maximize indexing/download capabilities while minimizing the chance of getting rate limited by YouTube. This isn't the exact same issue, but [this FAQ entry](https://github.com/kieraneglin/pinchflat/wiki/Frequently-Asked-Questions#my-source-isnt-indexing-on-the-schedule-i-set---what-gives) might help explain why.

It's also worth mentioning that _indexing_ takes up very little bandwidth. Downloading is more intensive of course, but if you've already downloaded most of a channel then the subsequent index tasks shouldn't make a noticeable difference on most networks

As a workaround, you may be able to use [custom yt-dlp options](https://github.com/kieraneglin/pinchflat/wiki/%5BAdvanced%5D-Custom-yt%E2%80%90dlp-options) with some of the [yt-dlp download settings](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#download-options). `--limit-rate` might help prevent Pinchflat from taking up too much bandwidth while also not impacting indexing too much.

**Comment by dashrandom** [comment]
@kieraneglin thanks a lot! I'll try that. Just one question regarding the base-config.txt file as the documentation isn't super clear, do we need to start the file with `yt-dlp` or can we just enter the config options e.g. `--limit-rate` into the file?

**Comment by kieraneglin** [comment]
The config files just need the command line arguments you want to add - no need to put `yt-dlp`. There's a [link](https://github.com/yt-dlp/yt-dlp#configuration) in the documentation to the yt-dlp configuration examples that might help!
