### ISSUE TITLE
[Triage] Not downloading new media after the initial scrape

### ISSUE THREAD

**Issue by dhruvbhutani** [kieraneglin/pinchflat#205]
Hi, 

As the title suggests, I'm unable to download any media after the initial scrape. Additionally, I have a hundred or so tasks listed under pending. 

I've set the indexing to daily so that shouldn't be an issue. Can I get some help on what I might be doing wrong and if there's a was to share logs?

**Comment by kieraneglin** [comment]
Hey there, thanks for the report!

There's a few reasons this could happen:

- there's a backlog of videos to download and they download on a first-in-first-out basis. If _some_ videos are downloading but not the ones you expect, this is what's happening. See [here](https://github.com/kieraneglin/pinchflat/wiki/Frequently-Asked-Questions#i-just-added-a-new-source-why-isnt-it-indexing-or-downloading) for details
- The source has been set to not download media. You can fix this by editing the source and selecting `Download Media`
- It's possible there was some transient YouTube issue that interfered with the way `yt-dlp` interacts with the site. This should have resolved itself by now, though

Can you confirm whether some videos have been downloaded since you posted this issue?

**Comment by kieraneglin** [comment]
In that case I'll need to know some more information. Would you mind attaching your logs?

**Comment by kieraneglin** [comment]
No problem! As I said above, the logs are stored in your Pinchflat config directory (within a sub-directory called `logs`)

**Comment by kieraneglin** [comment]
Hmm, it looks like the file didn't get attached. I _think_ you have to upload it to the issue directly rather than adding it as an email attachment

**Comment by dhruvbhutani** [comment]
[pinchflat.log](https://github.com/kieraneglin/pinchflat/files/15153731/pinchflat.log)
Done. This should work hopefully.

**Comment by kieraneglin** [comment]
That's a weird one! It definitely appears to be something to do with the BBC restricting viewership. Here are some examples of videos present on [that playlist](https://www.youtube.com/playlist?list=PL1XPWZmYWdc32Z5g3YoKJw4I8BC01c3fr) but they cannot be played:

- https://www.youtube.com/watch?v=GRxx6uN54P8
- https://www.youtube.com/watch?v=Ng4UCFoo61w
- https://www.youtube.com/watch?v=ZnG9Um_drjQ

All of these (and dozens more) are in the logs as having failed to download.

But when I look at [this playlist](https://www.youtube.com/@LoFiJapan213), it seems to have downloaded as expected since it doesn't have any restrictions on viewership.

---

I'm not sure how to approach this. I think what the app is doing is expected since that is, indeed, pending media that should be downloaded if it is ever able. I'll make some improvements to the download worker but I think for the moment I'm leaning toward the app working as expected in this weird case

**Comment by dhruvbhutani** [comment]
Interesting. Thanks for looking into it. I'll keep an eye out in case this
comes up again. Incredible app btw. Thanks for the effort.

[image: ltp|171441879350180]

**Comment by jl94x4** [comment]
Having this issue aswel.
