### ISSUE TITLE
[COPY] Download Cutoff Date

### ISSUE THREAD

**Issue by justcallmelarry** [kieraneglin/pinchflat#207]
Under the `Download Cutoff Date` it states that `Only download media uploaded after this date. Leave blank to download all media. Must be in YYYY-MM-DD format`

This is a bit ambiguous, as it doesn't really tell the the user if it will download things that were posted _on_ this date. I just tested and it does, so my suggestion would be to invert the text or specify that it also includes it, something like:
• `Only download media uploaded on or after this date. Leave blank to download all media. Must be in YYYY-MM-DD format`
• `Do not download anything uploaded earlier than this date. Must be in YYYY-MM-DD format`

**Comment by kieraneglin** [comment]
Hey! Thanks for the report (:

This is somewhat intentional (although a bit hand-wavey) as a quick-and-dirty solution to support all timezones. So in some TZs only the media uploaded _after_ that date will be downloaded, and in others it will pick up media on the same day.

I couldn't think of a way to concisely include that in help text (and I'm not convinced that doing so would reduce confusion). Please let me know if you have any copy suggestions with that in mind! Barring that I'd consider this expected behaviour from where I'm sitting 🤙

**Comment by justcallmelarry** [comment]
Ah yeah, that sounds a bit tricky I guess. Not sure if i can come up with a better copy for it 🤔 If you use the negativity-copy the statement holds true in both cases, but might still cause confusion.

I think this can be closed unless you want to keep it open for someone else to have input :) I just wanted to reach out since I found it confusing.

**Comment by kieraneglin** [comment]
I'll think about it but for this second I think I'll keep the copy as-is. But thank you for the report and please feel free to reply here or create a new issue if you think of something it can be changed to (:
