### ISSUE TITLE
[BUG] Can't cancel pro mode modal

### ISSUE THREAD

**Issue by justcallmelarry** [kieraneglin/pinchflat#208]
If you click anywhere which opens the pro mode modal you cannot exit the modal and any changes you did before entering are lost.

Only way to get around it is to reload the tab.

Perhaps add a cancel button that closes the modal? Being able to press esc to cancel would also be nice.

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report

I've intentionally disabled closing that modal since it's more an informational thing and I ultimately want people to be able to use the features. The only way to close it is to submit the form, but if you read it I think you'll see it's pretty agreeable (:

Not strictly related, but if you want to enable pro mode from the offset you can exec into your container and run `./bin/pinchflat remote` followed by `Pinchflat.Settings.set(pro_enabled: true)`. You can exit this shell by pressing ctrl-c _twice_

**Comment by sofmeright** [comment]
The accept button is completely restricted and I tried chrome firefox and chrome. This method you supplied above worked doing it from the container. But I do not know if this is behaving as desired as it is not possible to accept when putting "got it"

**Comment by skjonas** [comment]
I had the same issue where the accept button was restricted and I couldn't close the modal window. Activating websocket support in nginx proxy manager did the trick. Thanks!

**Comment by sofmeright** [comment]
Oh awesome, I actually ended up finding a fix using a command but now I
know this I'll add that to my nginx config! Thank you for the update! :)
