### ISSUE TITLE
[FR] Download one-off videos

### ISSUE THREAD

**Issue by fmartingr** [kieraneglin/pinchflat#212]
It would be awesome if one-off videos could be downloaded and organized through a profile using this tool. Sometimes I don't want an entire set of videos from a channel or a playlist but I want to archive interesting talks or videos that are shared with me in the same way the subscriptions (sources) are organized.

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

I've thought about this a _lot_. In fact, it's one of the first things I wrote in my "nice-to-have" notepad. The thing is, it's turned out to be really hard to meaningfully couple random videos to the idea of a Source or Media Profile. Not to say that it's impossible, but I've tried a few times and I haven't found a solution that feels correct.

What I've been doing in the meantime is that I created a new unlisted playlist on YouTube called "Videos to Download" and added _that_ to Pinchflat. New entries to that playlist will be automatically downloaded + managed and you can always click "Force Index" in-app to grab the latest. It's not perfect, but I think that's the best option for the time being.

I'll re-open this issue if I end up taking on a different approach!

**Comment by fmartingr** [comment]
Hey @kieraneglin that's actually really smart and perfectly suit my needs. I was so focused on downloading channel content that I forgot that this works for playlists too (and I have downloaded quite a lot of playlists manually with `yt-dlp`). Also this way I can create playlists by interest and I just need to add videos to those without the need of going to pinchflat, genius. Thank you!

**Comment by matejdro** [comment]
@kieraneglin unfortunately this workaround does not work with non-youtube sources (for example, Nebula) and it also seems a lot of work for a simple (adding an one-off video).

Often, I will stumble upon a video that I want to watch that is not part of my usual channels. I don't want to subscribe to that whole channel, I just want to add that one video.
