### ISSUE TITLE
[BUG] Unparseable URL (local network name:port)

### ISSUE THREAD

**Issue by justcallmelarry** [kieraneglin/pinchflat#216]
Related to https://github.com/kieraneglin/pinchflat/issues/214, I am trying to set up a hack using the current Apprise notifications.

However, if i enter an URL for an internal service, I get the following error (in the logs):
`11:37:34.177 [error] Failed to send new media notification for source 8: 2024-05-01 11:37:34,142 - ERROR - Unparseable URL http://transformer:8080/apprise/notify`

If I enter the container and curl the URL it is reachable, however.

**Comment by kieraneglin** [comment]
Thanks again for the report!

I suspect the issue is that you need to specify an _Apprise_ protocol instead of passing in a URL like you'd normally expect. The reason it gives a parsing error is because, in the absence of an Apprise protocol, it tries to discern the service you're trying to use based on the URL. Since it can't associate your URL with a service it knows about, you get an error. If you instead try something from [this list](https://github.com/caronc/apprise?tab=readme-ov-file#custom-notifications) it might work out more as you expect

That said, the Apprise integration really is meant for just getting notifications to Discord/Slack/email, stuff like that. I'm currently working on a different approach for something like #214 and I'll keep you posted! I think it'll be way easier to use my new integration once I get that up and running 🤙
