### ISSUE TITLE
[Triage] Could not fetch source details from URL

### ISSUE THREAD

**Issue by DCTS-uk** [kieraneglin/pinchflat#236]
when adding certain sources this error shows up. "could not fetch source details from URL"

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report

This error happens when `yt-dlp` is unable to determine any useful information about a source and usually happens when a URL is incomplete or a source is private. 

In order to diagnose this, I'll need some example sources that do this. Could you provide me with an example?

**Comment by JPDVM2014** [comment]
Not to reopen a closed issue, but I'm having the same problem. I tried the url that @DCTS-uk posted for Joe Rogan, and I got the same error. I'm on 2024.5.14,

The URL I was trying to add when I came across the error is: https://www.youtube.com/@StumpyNubs

I added my Youtube cookie thinking that was the issue, but I'm still getting an error. URL works ok in another yt-dlp based project.

**Comment by kieraneglin** [comment]
Don't stress about resurrecting this issue! If it's broke, it's broke (:

I've gotten a large number of reports about this today and I've been going back and forth on the cause and I think I've gone back to thinking it's related to YouTube A/B testing their new layout and the yt-dlp agent doesn't know what to do with it. I've seen a few similar reports on other projects and it's the only thing I can think of that would behave so inconsistently and temperamentally 

I'm going to keep looking into it to see what I can do to mitigate it, but if it is an upstream issue the yt-dlp team should be able to fix it soon! In the meantime, it would really help if someone was able to set their `LOG_LEVEL` environment variable to `debug` and then post your logs here when you encounter that issue. That'd make a huge difference in helping me triage 🙌🏻

**Comment by kieraneglin** [comment]
Yeah, I've tried over 50 accounts this morning and haven't seen this issue once. If it is an A/B testing situation, it may be because I'm not in their testing demographic.

So I'm asking for help! If this regularly happens to anyone, please set your `LOG_LEVEL` environment variable to `debug`, trigger this issue, then post your logs (which are stored in your Pinchflat config directory)

**Comment by JPDVM2014** [comment]
> Yeah, I've tried over 50 accounts this morning and haven't seen this issue once. If it is an A/B testing situation, it may be because I'm not in their testing demographic.
> 
> So I'm asking for help! If this regularly happens to anyone, please set your `LOG_LEVEL` environment variable to `debug`, trigger this issue, then post your logs (which are stored in your Pinchflat config directory)

Here you go. I tried the Stumpy Nubs channel again. I'm running on Unraid in case that makes a difference.

https://bin.lylapol.com/p/aQ5R7a

**Comment by kieraneglin** [comment]
@JPDVM2014 thank you! but that link is giving me a 404 - would you mind trying that upload again?

**Comment by JPDVM2014** [comment]
> @JPDVM2014 thank you! but that link is giving me a 404 - would you mind trying that upload again?

I changed it to paste the log instead of a download. This one should work.

https://bin.lylapol.com/p/epQENa

**Comment by kieraneglin** [comment]
No luck on that link, still a 404

**Comment by Danarlidge** [comment]
I'm also getting this when trying to add a channel, I can't upload the logs right now but I have attached a screenshot for now and will upload the logs in about an hour.
![IMG_1288](https://github.com/kieraneglin/pinchflat/assets/12379998/2669d6e0-3002-447f-acb7-cf18ac0f8156)

**Comment by kieraneglin** [comment]
Got it! I'll wait for those full logs. Thanks again!

In the meantime I might add a button in-app for downloading logs. Might make things easier when you're on mobile

**Comment by Danarlidge** [comment]
Hi kieraneglin,

I have managed to get the logs of me adding the source, i wasn't able to add it as a file. but here is a paste bin: https://pastebin.com/HH5ueKY8

Kind Regards,
Dan Arlidge

**Comment by kieraneglin** [comment]
Thank you!

Looks like I'll have to add some additional logging around these calls to get more meaningful info. I'll do so shortly. Thanks for your patience, everyone!

**Comment by JPDVM2014** [comment]
@kieraneglin Guess I need to go figure out why my self-hosted pastebin isn't working. But that's another problem. Lol.

Hopefully this link works. 

 https://pastebin.com/2a6u2cJy

**Comment by kieraneglin** [comment]
Okay, I've just pushed an update that improves logging around these failures! If someone could update to the latest and post logs after reproducing this issue, I would be very appreciative 🙌🏻

There's also now a way to download the logs in-app via Config > App Info in the sidebar

**Comment by Danarlidge** [comment]
Hi @kieraneglin,

I have attached my logs after the update.

Kind Regards,
Dan Arlidge
[pinchflat-logs-2024-05-15.txt](https://github.com/kieraneglin/pinchflat/files/15326948/pinchflat-logs-2024-05-15.txt)

**Comment by JPDVM2014** [comment]
@kieraneglin Here is mine. Same channel as before.

https://pastebin.com/G75r3ydS

**Comment by kieraneglin** [comment]
Thanks for the help, everyone! After working with the yt-dlp folks we at least know what the issue is, but we're still working out how to best solve it.

The gist is that `yt-dlp` causes an error when it tries to write to a read-only directory. It'll attempt this illegal write if it scans a video that is < ~48 hours old (ie: its only available format is a `m3u8`  [`#616`]) AND windows filename compatibility is enabled. The underlying reason isn't fully known (waiting to hear from the lead dev on `yt-dlp`) and we don't know why this appears to be a recent issue, but it's something!

I'm still trying to puzzle out what a temporary fix would look like. I can't disable windows filename compat because that would break SMB shares. I'll keep at it and see what I can come up with!

**Comment by kieraneglin** [comment]
Okay! I have a bandaid fix that will require a _lot_ of testing but ideally I'll release it tomorrow.

If anyone's feeling bold and wants to help me test, you can set your container manager to track `ghcr.io/kieraneglin/pinchflat:dev` instead of `ghcr.io/kieraneglin/pinchflat:latest`.

Thanks again to everyone for the help!

**Comment by JPDVM2014** [comment]
@kieraneglin I never even thought to check permissions since every other source worked.

Sure enough, the directory that Pinchflat created was owned by root. A simple `chown -R nobody:users youtube/` (probably unraid specific) fixed it.

Only problem is now it works no matter what, so I need to find another one that fails to test the dev branch.

**Comment by kieraneglin** [comment]
It actually should be okay for those base level directories to be owned by root (as long as the files and directories within it are owned by nobody). The core of the issue is definitely yt-dlp storing temp files somewhere it shouldn't under specific circumstances, but I'm glad to hear that things are working for you again!

**Comment by kieraneglin** [comment]
I'm happy with the testing and this fix is going out in ~30 mins as part of `v2024.5.16`! Thank you everyone for the help - especially @JPDVM2014 and @Danarlidge. If you set your container manager to track `:dev`, you can set that back to `:latest`.

I'm still working with the `yt-dlp` devs to get this fixed at the source, but for now I'm happy with this workaround!
