### ISSUE TITLE
[Question] Is enhanced bitrate supported?

### ISSUE THREAD

**Issue by ScribbleGhost** [kieraneglin/pinchflat#249]
Let me start by saying I absolutely love this project. 💖🙏 Where can I donate? 😀

I am obsessed with audio and video quality and I am paying for YouTube Premium. YouTube Premium has a feature called "enhanced bitrate":

> 1080p Premium is an enhanced bitrate version of 1080p. An enhanced bitrate provides more information per pixel, resulting in a higher quality viewing experience.
> \- [YouTube Help](https://support.google.com/youtube/answer/6308116?hl=en#zippy=%2Cother-premium-benefits%2Cpremium-badges%2Cchange-your-video-quality%2Cqueue-videos-on-mobile-devices-and-tablets%2Cpicture-in-picture-pip%2Cmodify-playback-with-premium-controls%2Ccontinue-watching%2Cyoutube-music-premium%2Cbackground-play%2Cwatch-videos-without-ads%2Cdownload-videos-to-watch-offline)

Example:
<img width="871" alt="Screenshot_2023_08_04_at_12 22 41_PM" src="https://github.com/kieraneglin/pinchflat/assets/49068170/338f8753-8052-4f71-a0e2-61403a1e6263">

Is it possible to use my own cookies or something like that to be able to get the enhanced bitrate?

**Comment by kieraneglin** [comment]
Thank you for the kind words! There is a donation link in the lower sidebar of the app (:

You can pass along your cookies, there's a blurb [here](https://github.com/kieraneglin/pinchflat/wiki/YouTube-Cookies) on how to do it. I haven't tested for this specifically, but the app looks for the highest quality mp4 in the specified resolution so I figure it should work! If it doesn't, I'll look into it to see how I can support that (as long as `yt-dlp` supports it)

Let me know how it turns out 🤙🏻

**Comment by kieraneglin** [comment]
Closing this since I've tested on my end and it seems to work! Feel free to re-open if I missed anything (:
