### ISSUE TITLE
[FR] Allow customization of more advanced yt-dlp options in media profiles (subtitle and thumbnail convert, format sort)

### ISSUE THREAD

**Issue by gandbg** [kieraneglin/pinchflat#394]
**Is your feature request related to a problem? Please describe.**
I'm trying to use PinchFlat to archive videos from various sources, mainly entire channels, and it seems that PinchFlat passes various options to `yt-dlp` that make archiving the highest-quality video possible a bit difficult. These options are:

1. `--convert-subs srt` - Sometimes YouTube subtitles can have various styling which is supported in the default WebVTT format used by `yt-dlp` if this option is not specified, but not in the basic Subrip/SRT format. [Example (Japanese subtitles at minute 6:30)](https://www.youtube.com/watch?v=0Cz8CjLq0fQ)
2. `--convert-thumbnail jpg` - YouTube's base format for the `maxresdefault` thumbnail (that i believe is the highest quality one) seems to be WebP. Converting to JPEG certainly make the file more compatible but it also reduces the quality by adding a new generation of lossy compression
3. `--format-sort res:2160,+codec:avc:m4a` - I'm assuming that the `res:2160` field changes based on the media profile's options so changing it to 8K should always get the highest-resolution file since that's the maximum YouTube currently allows.
	
	But the `+codec:avc:m4a` field, by preferring H.264/AAC files makes it so that you're skipping the VP9 or AV1 files, that YouTube sometimes provides for >=720p videos, that are more efficient in terms of compression ratio.
	
	The same principle applies to the audio codec, preferring the lower-quality AAC instead of Opus.

**Describe the solution you'd like**
I propose to add a few options within the media profile settings page to allow customization or removal of the `yt-dlp` described above.

**Describe alternatives you've considered**
I've considered using an old-fashioned bash script that executed yt-dlp commands but PinchFlat with its web interface provides a lot of other nice-to-haves like a summary of what has been downloaded and what has not, among others

**Additional context**
Due to the fact that not many users may need to change these settings from the defaults, maybe making them advanced options may remove some clutter from the media profile settings page

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

These are all fair points! Unfortunately, these won't be super simple to implement since there's no way to negate existing `--convert-subs` or `--convert-thumbnails` options. Yours is a totally valid use case as far as I'm concerned, but in absence of something like `--no-convert-subs` this would be a much bigger refactor than it would otherwise appear. I'll start by talking to the `yt-dlp` team and see if they have any interest in me adding those `--no-convert-subs` and `--no-convert-thumbnails` options since that would make things WAY easier.

For your 3rd point, there _may_ already be a solution available. Keep in mind that `--format-sort` does no conversion, it only changes the order of preference. With that in mind, you can go to Config > Settings and change the global preference for preferred codecs, although I acknowledge this doesn't solve everyone's use case.

re: `[...] are more efficient in terms of compression ratio`, I will also say that maximizing storage efficiency isn't strictly a goal of this app. If the provided codec is equivalent in quality, that's considered "good enough" in my eyes even if a different codec could shave off a few bytes.

Anyway, I'll check with the yt-dlp team and start looking into this!

**Comment by gandbg** [comment]
Thank you for such a quick response!

> For your 3rd point, there _may_ already be a solution available. Keep in mind that `--format-sort` does no conversion, it only changes the order of preference. With that in mind, you can go to Config > Settings and change the global preference for preferred codecs, although I acknowledge this doesn't solve everyone's use case.

Well, that does solve my problem. I should've checked that page before writing the first comment but I guess that you were able to rephrase it into a new feature request, so that's awesome!

**Comment by kieraneglin** [comment]
I've made a PR for yt-dlp here: https://github.com/yt-dlp/yt-dlp/pull/11066

Hopefully they approve and merge it!

**Comment by kieraneglin** [comment]
Good news! They merged that pull request so you will be able to disable conversion of thumbnails and subtitles once the next version of yt-dlp releases. Once that's in, I'll update with how to practically set that up for archiving purposes

**Comment by gandbg** [comment]
Thank you (and the yt-dlp developers) for implementing this!
Not gonna re-open the issue at least for now since I don't think you've missed anything
