### ISSUE TITLE
Is there a way to do text processing on video titles?

### ISSUE THREAD

**Issue by UntouchedWagons** [kieraneglin/pinchflat#397]
For example I'd like to download this playlist: https://www.youtube.com/playlist?list=PLU2851hDb3SEesCjVCmseu60aJht1DQwh but I don't want the entire video's title in the file name when downloaded; instead of `Hermitcraft 6: Episode 5 - FLYING & DIVING` I'd just want `Flying & Diving`, so normalization would be needed too. Is this something that can be done?

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

There is a way to do that (at least the processing part), but it's 100% handled by yt-dlp rather than Pinchflat. [Here](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#modifying-metadata) are the yt-dlp docs on this and [here's](https://github.com/kieraneglin/pinchflat/wiki/%5BAdvanced%5D-Custom-yt%E2%80%90dlp-options) how you use those options in Pinchflat.

If you get stuck, the yt-dlp discord is really helpful for this kind of thing!
