### ISSUE TITLE
[Triage] Download Series Images doesn't work when Source has download cutoff date

### ISSUE THREAD

**Issue by at012423** [kieraneglin/pinchflat#417]
**Describe the bug**
Download Series Images doesn't work when Source has download cutoff date

**To Reproduce**

1. Create a test media profile with the Download Series Images option checked
2. Add a source with a download cutoff date
3. Check folders, see there is not any poster/banner in the root directory
4. Add another source without a download cutoff date
5. Check folders, see that there is a poster/banner

**Expected behavior**
Poster/banner to download as long as "Channel" is the source, regardless of cutoff date

**Screenshots**
N/A

**Diagnostic info**

- App Version: 2024.10.2
- yt-dlp Version: 2024.09.27
- Apprise Version: v1.9.0
- System Architecture: x86_64-pc-linux-gnu
- Timezone: America/Chicago

**Additional context**

N/A

**Comment by at012423** [comment]
Somehow after retesting today, was unable to replicate. Will close.

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

You're not going crazy! This seems to be an intermittent issue for some users that I suspect is caused by YouTube running experiments for some users that yt-dlp isn't equipped to handle (see #416). I'll be looking into this and please let me know in #416 if you start seeing this issue again!
