### ISSUE TITLE
[FR] Add the option to setup the time for indexing & downloading 

### ISSUE THREAD

**Issue by sigulete** [kieraneglin/pinchflat#422]
It would be useful to have an additional control to schedule indexing. 
Currently, it is possible to choose the frequency, but it is not clear what time of the day it happens. As an example, I would like to index all my subscriptions at 6am (local time) every day.

Otherwise, this is a great app !!

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

I'm going to close this in favour of #406 since the underlying mechanism would ultimately be the same. That said, I don't think it's likely that this feature will be implemented for the reasons outlined [here](https://github.com/kieraneglin/pinchflat/wiki/Frequently-Asked-Questions#my-source-isnt-indexing-on-the-schedule-i-set---what-gives).
