### ISSUE TITLE
Native installation?

### ISSUE THREAD

**Issue by SpaceAgeHero** [kieraneglin/pinchflat#423]
Hey,
this looks pretty cool.
I'd like to install and use this without Docker on Arch Linux ARM. Is this possible?

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

It's _possible_ but Docker is strongly recommended and, bluntly, I don't have the capacity to help with non-docker setup and troubleshooting.

You could look into [Elixir release](https://hexdocs.pm/mix/Mix.Tasks.Release.html) since they create a standalone binary that can be run natively on the same architecture/OS that builds it, but again that's not something I have the ability to support.

Overall I'd recommend sticking with Docker.
