### ISSUE TITLE
[Triage] Date / Time in the UI not respecting local time set with TZ

### ISSUE THREAD

**Issue by sigulete** [kieraneglin/pinchflat#429]
**Describe the bug**
The date and time across different windows in the UI are mixed. In some cases they show local time, but in other cases they show UTC time.

  **To Reproduce**
Local time is shown at:
mydomain (home)

UTC time is shown at:
mydomain/sources/x/media/xxx (medial detail)
mydomain/sources/x (source details)
all task windows

  
**Expected behavior**
Local time based on TZ configuration to be used across the board.

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

Most of these are actually expected - the details on the profile/source/media item page are intentionally _raw_ details for the purposes of helping me develop and troubleshoot for users. I've been meaning to provide a better user interface on these pages for a while now, but for the time being this is expected behaviour.

I agree that the `Scheduled At` field in the tasks table should respect your TZ since that's not presented as "raw" information. I'll make that change!
