### ISSUE TITLE
[Triage] Pinchflat is indexing all the sources at the same time

### ISSUE THREAD

**Issue by costaht** [kieraneglin/pinchflat#438]
**Describe the bug**
I noticed that as soon as I start the container, Pinchflat starts indexing all the sources simultaneously, and it does this for the **entire** channel, which consumes a lot of CPU.

**To Reproduce**

1. start the container
2. run `ps -fe | grep pinchflat`
3. observe all the instances of yt-dlp running in the background

**Expected behavior**
I believe Pinchflat should scrape only one channel at a time and only up to the Download Cutoff Date. That can be achieved by using `--break-on-reject --dateafter now-3days`

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

I'd be surprised if this was the case, but it's possible! I have concurrency limited to two workers for indexing and two for downloading for a total of 4 concurrent yt-dlp operations (see [here](https://github.com/kieraneglin/pinchflat/blob/master/config/runtime.exs#L47)). You can decrease this to one worker for each (two total) by setting `YT_DLP_WORKER_CONCURRENCY` but this usually isn't necessary. I can't replicate this locally and I haven't received any other reports of this (despite this logic being unchanged for months), but I would be curious to see your output of `ps aux | grep runner`. 

High CPU usage is often caused by ffmpeg assembling a video, especially if you are using the sponsorblock integration. Within reason this is both expected and unavoidable. Getting back to me with the result of that command above help!

As for indexing, it is intentional and expected that indexing covers the entire channel and ignores filters (see [here](https://github.com/kieraneglin/pinchflat/wiki/Frequently-Asked-Questions#what-is-indexinghow-does-it-work)). I recognize this isn't strictly the most efficient approach, but as I see it the benefits outweigh the downsides. Besides, indexing itself should use fairly modest resources compared to actually downloading and assembling the videos.

**Comment by kieraneglin** [comment]
Thanks for the followup! I'll close out this issue

I've thought about creating a Discord server a few times, but ultimately I don't have much time in the day to devote to support in that way. At least with GitHub issues I can address them as time permits rather than there being an expectation of immediate-ish feedback.

That said, I'll keep considering it! If I end up making one, I'll put a link to it in the in-app sidebar 🤙
