### ISSUE TITLE
[Triage] wrong permissions

### ISSUE THREAD

**Issue by Foxy-NC** [kieraneglin/pinchflat#443]
I use Unraid and installed pinchflat a few days ago.
It worked right away after installation but after restarting the container I realized it had changed the owner permission of my files recursively in /downloads
Previously it was "nobody" and it changed to the "unraid" user.

I guess this is due to the extra parameter "--user 99:100", 100 meaning the unraid user.
I changed it to "--user 99:98" and it seems to work as expected now without changing to owner permissions.

Could you correct to the template accordingly?
Thanks

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

I suspect this is a configuration issue with your Unraid instance. I also use Unraid and it seems that the default Docker user (`nobody`) has the UID/GUID of 99:100. There are lots of other containers that use 99:100 as a default and [here](https://github.com/cross-seed/unraid-template/blob/master/cross-seed.xml#L26) is just one example.

I'm not sure where this configuration difference came from, but thankfully the fix is as simple as changing the parameter as you've already done!

> after restarting the container I realized it had changed the owner permission of my files recursively in /downloads

Just to be clear, the app won't recursively change any permissions. It'll apply the permissions of the user it's run as to the files it's actively working with but it won't automatically change the permissions of unrelated files
