### ISSUE TITLE
[FR] Scheduled downloads

### ISSUE THREAD

**Issue by Kadz93** [kieraneglin/pinchflat#444]
Hi, first of all thanks for your work I really like it !

I think it would be a good idea to be able to schedule the download times or indexing times.

My problem is that I'm working 100% at home and don't have a super fast Internet connection.
Therefore it would be great to be able to limit the "active" times for pinchflat to after work hours or even into the night.
Of course that can collide with the index frequency.

Let me know what you think of my idea l, o think it's a feature that can be added pretty easily.

Greets fron germany

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

I'll be closing this issue since this is already being tracked in #406. To be perfectly honest, I don't suspect this will be something I add soon since it's actually extremely complex to do it right. But if you subscribe to that issue I linked earlier it'll let you know if I make this change!
