### ISSUE TITLE
[FR] Increase information density on desktop

### ISSUE THREAD

**Issue by bretthysuik** [kieraneglin/pinchflat#458]
**Is your feature request related to a problem? Please describe.**
Information density is quite low on desktop. Examples:

1. Video title is heavily truncated but there is plenty of empty space between the truncated title and the Edit button:

![image](https://github.com/user-attachments/assets/2e748ef7-671e-4b15-a320-9d48a55a483b)

2. Video titles are heavily truncated and there's a lot of extra padding between columns in every table, which could be used to display more of the title:

![image](https://github.com/user-attachments/assets/02058f1a-ae94-46c0-8df4-3b93ea99dba0)

![image](https://github.com/user-attachments/assets/9717f408-3ef0-4a6c-a18b-e7b2ac43e1ed)

**Describe the solution you'd like**

Reduce the amount of padding between columns in every table, and reduce the amount of truncation for titles everywhere. Mockup (imagine the titles are expanded to fill available horizontal space):

![image](https://github.com/user-attachments/assets/acd15da3-1723-4b72-a7a2-0e1adfcc0a4c)

I understand the titles need to be truncated for mobile, but I think they need to be less heavily truncated when the viewport is wider than mobile.

**Comment by kieraneglin** [comment]
Hey there! Thanks for the suggestion (:

I don't disagree on the merits (apart from the fact that I find `Indexed At` _very_ useful), but the issue for me is my competencies. I'm primarily a backend dev and I have _zero_ love or innate talent for creating UI. It's a means to an end and all that.

This is to say that, although these are good suggestions, _I_ won't be able to look into this until many other heavy-hitter backend items are handled. But since HTML/CSS are common skillsets I encourage anyone who wants to get involved to see about turning some of these changes into PRs! I'm happy to answer any questions about how Elixir works on the frontend.

I'll leave this issue open to track these changes, but at the moment the best option for getting these done any time soon is for me to try and farm these changes out 🤙

**Comment by bretthysuik** [comment]
Looks great, thanks!
