### ISSUE TITLE
[FR] Bulk delete videos in the sources downloaded tab

### ISSUE THREAD

**Issue by Mozart409** [kieraneglin/pinchflat#469]
**Is your feature request related to a problem? Please describe.**
My current setup is, that jellyfin only has a read-only bind to all my downloaded media, and it would be nice to delete files from pinchflat.
It's difficult to delete single files from a source. The current steps to delete a single file are as follows:

1. Sources
2. Download tab
3. Select the video
4. open actions dropdown
5. delete file

That's too many steps

**Describe the solution you'd like**
An edit mode in the Downloaded Tab to select multiple files which then can be deleted

**Describe alternatives you've considered**
This functionally is partly covered by the retention days, but occasionally, I would rather not set a retention period as it would delete multiple files because pinchflat downloaded them on the same day.

**Additional context**

**Comment by kieraneglin** [comment]
Hey there! Thanks for the suggestion (:

Totally agreed! I'm going to close this specific issue since this request is already covered in #346, but this is one of the next big-ticket features I'm looking to add once I get some bugfixes completed.

Anyway, keep an eye on #346 for any news! You can subscribe to an issue if you want updates on it
