### ISSUE TITLE
[Triage] Adding New Source Failing 

### ISSUE THREAD

**Issue by cmdlabtech** [kieraneglin/pinchflat#470]
**Describe the bug**
When adding a new source (in this case, Youtube Channel), the UI stalls and eventually goes to a 502 error and never adds source to list.

**To Reproduce**

1. Go to 'Sources'
2. Click on 'New Source'
3. Scroll down to 'Save Source' button
4. Click on 'Save Source'
5. Wait until page timeout to get 502 error (screenshot below)

**Expected behavior**
Pinchflat adds source to list, starts indexing, and starts downloading

**Screenshots**
![image](https://github.com/user-attachments/assets/3a97400b-6772-4b06-b991-fb9e6c3bb16e)

![image](https://github.com/user-attachments/assets/501fdc95-4a48-4d11-a2e1-9eb01b49a5dd)

**Diagnostic info**

- App Version: 2024.10.30
- yt-dlp Version: 2024.10.22
- Apprise Version: v1.9.0
- System Architecture: x86_64-pc-linux-gnu
- Timezone: America/New_York

**Additional context**

Tried direct IP to Pinchflat and proxy through NPM. Tried with Linus Tech Tips channel and Dbrand channel as test links.

[pinchflat-logs-2024-11-13.txt](https://github.com/user-attachments/files/17736869/pinchflat-logs-2024-11-13.txt)

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

I've looked into your logs and I'm seeing a lot of errors like this: `Unable to download API page: _ssl.c:975: The handshake operation timed out (caused by TransportError('_ssl.c:975: The handshake operation timed out'))`. Looking through yt-dlp issues like this https://github.com/yt-dlp/yt-dlp/issues/4931, it looks like this is caused by a network configuration issue. Could be anything from a bad proxy setup to a DNS blackhole that's blocking too much to any manner of other firewall issues.

This isn't something I can fix in-app, but I would look into those and see if the requests to youtube are getting dropped somewhere!
