### ISSUE TITLE
Drive change

### ISSUE THREAD

**Issue by memaxwelll** [kieraneglin/pinchflat#491]
Hey!
Great new update :) 

I was wondering if someone here tried to copy / move their library to another drive?

I have approx. 23K videos across two drives and want to upgrade these two drives to larger ones.

How would one go about copying / reindexing? 
Maybe using the DB? But that would mean overwriting the paths in the DB right?

Regards
Max

**Comment by kieraneglin** [comment]
Hey there! Thanks for the request (: Just a heads up that everything I'm about to say is speculation and untested.

Since the app uses Docker to map its volumes, it shouldn't have any knowledge about how you store your media per se. This works to your benefit because you _should_ be able to move your Pinchflat download directory to another drive/machine/whatever and as long as the Docker volume mount is updated appropriately the app should just work as normal.

If you go for this, make sure you turn off the Pinchflat container during the move. Just to minimize the chances of things going wonky

**Comment by memaxwelll** [comment]
Wow!
Thanks for the fast answer :) 

I will check once the new drives arrive.

Have a nice evening/day!

**Comment by kieraneglin** [comment]
Thank you! I'm going to close this issue for now - please re-open it or create a new one if you encounter any problems!
