### ISSUE TITLE
[Triage] Pending count shows entire YT channel despite 90 day limit

### ISSUE THREAD

**Issue by joestump** [kieraneglin/pinchflat#492]
**Describe the bug**

My "Pending" count for SpawnWave is 3500+ despite setting a 90 day threshold.

**To Reproduce**

1. Add SpawnWave as a source
2. Set threshold to 90 days
3. Wait for it to index
4. You'll see thousands of Pending jobs

**Expected behavior**

Pending jobs are not created for videos that are greater than the threshold.

**Screenshots**

<img width="938" alt="image" src="https://github.com/user-attachments/assets/4b3d8091-3d6b-4c52-9ab1-62e52c962ea8">

<img width="1423" alt="image" src="https://github.com/user-attachments/assets/9512776f-9cac-4924-a95d-687a8756b1ea">

**Diagnostic info**

Dude, this "Copy Diagnostic Info" feature is genius - totally stealing this idea! `<!-- Go to Config > App Info > Copy Diagnostic Info and paste that here -->`

- App Version: 2024.11.27
- yt-dlp Version: 2024.11.18
- Apprise Version: v1.9.0
- System Architecture: x86_64-pc-linux-gnu
- Timezone: America/Los_Angeles

**Additional context**

First tried updating the threshold after seeing 3,700+ in the Pending queue. That didn't seem to "take" so I tried deleting it and re-adding it, but it's happily indexing very old videos still and prepping them for download.

**Comment by joestump** [comment]
I see my confusion now. You need _both_ retention days _and_ the cutoff date. Would be nice if one of the two were the case: 

* Switch the cutoff date to "don't download older than X days".
* Default cutoff date to `$now - $retention_days` if cutoff date is not specified, but a retention days value is. 

After updating the cutoff date, Pinchflat did do what I expected and cleared out the Pending queue.

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (: - glad to see you got it figured!

For your first point, I agree that it could be improved. I have an open issue for that in #451. The proposed changes won't do exactly what you mentioned, but there should be a UX improvement nevertheless!

For your second, _I_ agree but that change was actually made in response to a lot of user requests. Apparently people like to download an entire channel's videos and use the retention date to automatically delete them en masse after, say, 2 months. This works since the retention date doesn't compare against when the media was uploaded by the channel, but rather when it was downloaded to your machine.

I think there's room for improvement there as well so I'll link your comment in #451. I'll also dig in and see if I can find the original opposition a default cutoff date so I can be sure I know where they're coming from 🤙
