### ISSUE TITLE
Ignore Season metadata?

### ISSUE THREAD

**Issue by HybridSarcasm** [kieraneglin/pinchflat#511]
I'm grabbing https://www.youtube.com/@EngineeringMindset and there is 'season' metadata being written to the .NFO files.

```
  <aired>2015-07-05 00:00:00Z</aired>
  <season>2015</season>
  <episode>0705</episode>
  <genre>YouTube</genre>
</episodedetails>

```

Jellyfin is (I assume) seeing this and creating a season for every single video. This particular channel doesn't have seasons. It's just a huge repo of videos. Is there anyway to ignore this season metadata upon extraction so it is not written to the .NFO files, or the videos themselves ?

**Comment by kieraneglin** [comment]
Hey there! Thanks for the question (:

There isn't a way to do that in-app. Some media centre apps require media be organized into seasons and I arbitrarily chose to categorize them by year since that makes the most sense to me. That said, Jellyfin _should_ handle this somewhat sanely by putting all the videos from a given year into the same season:

![Screenshot 2024-12-13 at 9 41 10 AM](https://github.com/user-attachments/assets/97276f4d-3236-4196-9b4a-0a14ed0b9ca3)

**Comment by Patriot2407** [comment]
I have the same problem. There is a season folder and a folder for every single episode.
![Screenshot_2024-12-31_11-25-39](https://github.com/user-attachments/assets/635fade4-5f90-4dd9-aa83-d0764634c773)

**Comment by kieraneglin** [comment]
@Patriot2407 Did you use the Media Center preset when creating your media profile? It doesn't look like the names are in the correct format

**Comment by Patriot2407** [comment]
Yup, I just confirmed that was my issue, thanks, I'm all set now!
