### ISSUE TITLE
Permission problems with pinchflat using on proxmox

### ISSUE THREAD

**Issue by EdmunDenzel** [kieraneglin/pinchflat#516]
Hi,

thanks for the really nice work on this tool. Im unfortunately having some problems get it running on my configuration. Maybe you are able to help me out?

I am trying to deploy a Docker container (running the pinchflat service) on an LXC container hosted on Proxmox. The container should access an SMB share mounted on the Proxmox host, but I am encountering a permission denied error when trying to mount a host directory into the container.

i created a user pinchflat in the lxc container and also on the proxmox host. i ensured that tthey have the same uid and gid.
i added pinchflat to the group on my proxmox host which is owner of the directory i want to use.

and i started the container with this user.

this is my error:
Failed to deploy a stack: Network pinchflat_default Creating Network pinchflat_default Created Container pinchflat-pinchflat-1 Creating Container pinchflat-pinchflat-1 Created Container pinchflat-pinchflat-1 Starting Error response from daemon: error while creating mount source path '/mnt/pinchflat/downloads': mkdir /mnt/pinchflat/downloads: permission denied

i checked permissions and i checked the smb share. nothing helped.

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

Unfortunately I don't have any advice here because I've never used Proxmox. That said, the permissions issue you're seeing seems pretty similar to other issues in this repo so I encourage you to check those out! #426 specifically might be helpful

**Comment by Clete2** [comment]
Hey OP, I run Proxmox too. I highly recommend making a VM for Docker, it's easier and better supported than LXC management. I know that's probably what you don't want to hear, but take it from someone who did both that I very much prefer the VM method.

**Comment by EdmunDenzel** [comment]
@kieraneglin 
Thanks for this. I will research the thread you mentioned and maybe i find a solution.

@Clete2 
Thanks also. I was thinking about this before i setup the container.
In the beginning i tried to run this without docker in a lxc container itself. But also had the permission problem.
My hope was that with running pinchflat in a docker container it would solve the issue. But this wasnt the case.

How is your setup?
At the moment i run proxmox and the single tools in each a lxc container.
But some guys are running proxmox with one virtual machine with docker installed. And then for each tool a docker container. I think this would made the permission topics easier. 
But Im not sure whats the better solution.

Did you get pinchflat running on proxmox with a external volume?

**Comment by Clete2** [comment]
@EdmunDenzel Here are the relevant bits of my server:

* zfs `rpool` - SSD mirror where Proxmox and all VMs are installed
* zfs `tank` - HDD RAIDZ2 where all data is stored
* `docker` VM (actually `dockerUbuntu` because I used to use CentOS)

On main server:
* `tank/media/other` is storage for my Pinchflat, I set `zfs set sharenfs=no_root_squash,rw=@<IP of Docker VM>/32`
* `chmod 755 /tank/media/other` This is frustrating, I wanted less, it is owned by root, but I don't know NFS well enough.

In VM:
* `/etc/fstab/` contains `MYSERVERHOSTNAME:/tank/media/other /mnt/otherMedia	nfs rw,hard 0 0`
* In docker-compose.yml: 
```
    volumes:
      - ./:/config
      - /mnt/otherMedia:/downloads
```

Note I am storing `config` local to the VM, and only downloads are going to the storage HDDs.
