### ISSUE TITLE
[FR] Configurable Fast Index Time Interval

### ISSUE THREAD

**Issue by mattsmithdev** [kieraneglin/pinchflat#518]
**Is your feature request related to a problem? Please describe.**
I've been using fast index across most of my sources and it's been working well, but I believe it checks every 10 minutes. I would like to configure that to a higher number in my case, since I don't need it to check that often.

**Describe the solution you'd like**
An advanced configuration option for the fast index check interval per source (if possible).

**Describe alternatives you've considered**
Using the standard index, but I like how fast index picks up the new videos right away.

**Additional context**
Using the docker image on Unraid

**Comment by kieraneglin** [comment]
Hey there! Thanks for the request (:

Would you mind expanding a little on _why_ you'd like to increase the number? If you aren't using an API key for fast indexing then it uses an RSS feed that's not rate limited as far as I can tell.

Most people want the checks to be _more_ frequent so I'm curious to hear your use case!

**Comment by mattsmithdev** [comment]
Hey - First off great product and it's working absolutely as advertised. This is purely a resource optimization request.

The channels I watch might have a video a day, some even less than that. I originally was using the 'slow index', but it won't then grab the video until it runs again, which I set to be longer per the recommendation. When I use the fast index it of course grabs it almost right away. It also just makes sense how you designed it, not having to do a full pull every time. I really like that.

I'm using it in Unraid running as a container. I'm trying to keep resource usage as low as possible and see the container is steadily using resources, even more than my *arr containers. It's not much, but for my needs it's not necessary. If I can just have it check less frequently I'm hoping I can lower the usage.

**Comment by kieraneglin** [comment]
Fair enough! In that case, I think I'll close this issue since fast indexing specifically is extremely light on resources. It's a simple HTTP request that only spins off an intensive operation (like downloading) if it finds something new. In other words, there's next to no resource utilization penalty for fast indexing if it doesn't find anything new to download

re: usage, that's an unfortunate side effect of yt-dlp. It's quite resource intensive under-the-hood and I've noticed that it doesn't always free memory as it should. The re-assembly of videos post-download can also be quite CPU and memory intensive, but that's truly unavoidable when it comes to FFmpeg operations

Thanks again! Feel free to re-open if I missed anything
