### ISSUE TITLE
[Triage] Idle CPU usage seems quite high 

### ISSUE THREAD

**Issue by nebula-it** [kieraneglin/pinchflat#522]
**Describe the bug**

The idle CPU usage seems quite high compared to other similar tools e.g This is a comparison of pinchflat v/s https://github.com/alexta69/metube running on same hardware and both dont have any downloads at the moment. 

![image](https://github.com/user-attachments/assets/f9a249b9-e31f-4340-952b-81ba8d7b1429)

**To Reproduce**
Run both Pinchflat and https://github.com/alexta69/metube (`docker run -d -p 8081:8081 -v /path/to/downloads:/downloads ghcr.io/alexta69/metube`) and observe the CPU usage in `docker stats`

**Expected behavior**
The CPU usage at idle should be quite low compared to what it is

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

There are a few differences to note here. One is that metube is a much more simple application than Pinchflat - even if there are no downloads, Pinchflat has processes to keep the connection to the database open, trigger indexing passes, run checks for whether to redownload/delete existing media, among other things. It's a bit of an apples to oranges comparison in that sense.

The other is that Elixir as a programming language handles resource utilization fundamentally differently than many other languages. There's a slightly higher idle cost in exchange for significantly more efficient resource usage when the app is under significant load. Of course this doesn't matter for the selfhosted context, but I picked Elixir as a language since I love working with it and it has best-in-class task concurrency support
