### ISSUE TITLE
Create Community Site for PinchFlat

### ISSUE THREAD

**Issue by dozerman-ms** [kieraneglin/pinchflat#526]
If there is a need, a minimal and unofficial, well-moderated forum that is more user-focused and less technical than the github issues.

**Comment by kieraneglin** [comment]
Hey there! Thanks for the suggestion (:

I'll think about this while I'm away on winter break, but I don't know if the maintenance burden is worth it. At that point I would probably rather start up a discord server, but I've been hesitant to do even that since I don't have the capacity to moderate a server and be answering questions at all hours. I've created and managed large discord servers before and it can be quite difficult if you don't stay on top of moderation

I'm sure I'll have to start up a discord server at some point, but I want to make sure that I set it up correctly for both myself and the community. I'll keep thinking about this for the rest of my winter break and if I add a server I'll post it in the release notes and it'll be in the sidebar of the app (:
