### ISSUE TITLE
Request: Better Compatability w/ Kodi, Plex, and Jellyfin

### ISSUE THREAD

**Issue by hernandito** [kieraneglin/pinchflat#68]
I think only a few small things are needed to make better compatability w/ Kodi and Plex (not 100%).

I am not exactly sure what can be scraped by Pinchflat when running. From what I can surmise, the below looks doable.

In my server I have a folder named "YouYube" (/mnt/user/Media/YouTube. This is the folder mapped to the docker. For this testing below, I have only done one channel. In my case it's:
     https://www.youtube.com/@BaumgartnerRestoration

Is it possible to get an image for the channel itself? In the channel's home page, I see a banner looking image. I downloaded this image, and named it **banner.jpg** and it is in the root folder for the one source. In Kodi, I added a source and told it contains TV shows, but excludes them from scanning AND to scrape local information. I had to give it a TV category so I can get "banner view" in my skin. 

This is what it looks like when I I go to my YouTube source:

![image](https://github.com/kieraneglin/pinchflat/assets/787317/50c52c2a-7d61-4fbb-9001-7b204fd9e283)

When scraping and downloading each video, you are saving a .webp image as a thumbnail of the video. Can you please create a JPEG **copy** of this file and name it **folder.jpg**. This way, we a when browsing the selected channel in Kodi, you get image below. I converted the .webp image into a folder.jpg file.

![image](https://github.com/kieraneglin/pinchflat/assets/787317/096e0bc2-cfd1-4549-b4e8-6938aeced56c)

I am not sure what other info can be scraped, but It would be nice to get additional info and store it in Kodi compatible .nfo files. 

I think Plex can use the same images... as this is what my media library contains, and I do have Plex for my family members.

I think this has the potential to be the next *arr application.... pincharr. 

Please let us know your thoughts.

Thank you!

**Comment by kieraneglin** [comment]
That's a fair shake and something I've been thinking about a LOT. The `.nfo` question is a big one that I'll be looking into someday soon, but for now I'll focus on your other asks. I'm also not sure if a banner can be extracted as part of `yt-dlp` but I'll poke around and see what options are available to me.

A big part of my motivations here are around NOT overbuilding for every scenario and remaining agnostic to what the user will do with the data (as much as is reasonably possible, anyway). Things like calling a banner `folder.jpg` ultimately imposes many assumptions about how a user will want their data parsed.located in a way that I rapidly think will become unmaintainable.

This is just me thinking out loud so I can't commit to this, but one approach I was thinking of here is allowing user-specified lifecycle-related scripts. Something like "after downloading a video, I'll run this script with some relevant arguments passed". This would let someone create a script that, for example, re-encoded and copied the thumbnail with a new name or something like that. It lets the app remain agnostic about what you'll do with the data while still opening the gates for a deeper Plex/Kodi/whatever integration.

Ideally I could create a few baseline scripts myself for some common use cases (like yours) to minimize the need for a user to be able to create bash scripts. Or maybe I could have a community repo where useful scripts are shared. Again, just thinking out loud!

---

It's still early days and I'm going to be re-assessing many aspects of the download process as the app's place in the ecosystem becomes more clear. I'll be sure to update here if I make any changes that could help out :)

Thank you for your kind words and your feedback 🤙

**Comment by hernandito** [comment]
Thanks for the feedback. It all makes sense. I am excited to see this grow!

As it is, I cannot imagine myself subscribing to a ton of channels. I can manually tweak each channel to add the banner/logo image. 

The .webp is more of a challenge to do manually as there are dozens of folders to process. I will look into scripting this. A quick Google resulted in this:

![image](https://github.com/kieraneglin/pinchflat/assets/787317/56d06ea4-2d3b-4d10-951c-283cc4670e26)

HOWEVER... when I go into the Docker's console, it does not allow to manually install any apps (which I would likely need if there is some type of .webp to .jpg command line package). 

Is there a way to unlock user' being able to execute sudo type commands in the console?? I have never run into a container that does not allow this.

**Comment by kieraneglin** [comment]
@hernandito I've also made some changes re: docker permissions that you can see in #71. I'm assuming you're using this through Unraid so there will be a small change you have to make there:

- In Unraid, edit the `pinchflat` docker configuration
- Edit `Console shell command` from `Shell` to `Bash`

This is set automatically for all new installs, but Unraid won't retroactively update your config. It's not even technically needed, but it's a nice quality-of-life thing.

---

You can always run as root by editing the Pinchflat docker config > enabling "Advanced View" in the upper right > and changing "Extra Parameters" from `--user 99:100` to `--user 0:0`. From that point on, the console will automatically log in as `root`. That said, I don't think that's always the best solution. Doing this will make root the owner all files/folders created by Pinchflat which can make interaction with other apps difficult if they don't have sufficient privilege. This can be desirable in some cases, but I'd consider it an advanced use case and it's probably not the recommended default. Also, if you use `--user 0:0` you can _never_ go back to `--user 99:100` because that user won't be able to interact with any files/folders created by root.

If you want to just run one-off commands as root, I recommend  keeping the current `--user 99:100` configuration and running `su` in the console to assume the root user as-needed! #71 is what allows this to happen so it won't work until that's deployed.

---

As a final note, it's probably best to avoid running too many commands like `apt update` that'll be overwritten every time the docker is updated. There really shouldn't be much of a need for root access, but I added it in because I think it's a reasonable request for advanced users like yourself 🤙

**Comment by kieraneglin** [comment]
I've just deployed [this changeset](https://github.com/kieraneglin/pinchflat/compare/v0.1.0-alpha.1...v0.1.0-alpha.2) to Docker Hub which covers some of the points you brought up! That should be available as an update within an hour or two, or you can force update now if you'd like.

I'm going to close this issue - not because it's done, but because there were a few good points that I'd like to tackle one-by-one so I created individual issues for each of those points. See #73 and #77 (and less importantly #72).

Thank you again for the feedback!

**Comment by kieraneglin** [comment]
@hernandito I think this is good to go! I've added support for episode and source-level NFO files, as well as adding banner/fanart/poster images at the source level.
